### ISSUE TITLE
item.poop.name with no texture

### ISSUE THREAD

**Issue by ktole1999** [SteveKunG/More-Planets#70]
this is on a new server. i have 2 items in my inventory named this and i have no idea what it is. belongs to mo planets mod.

any help is greatly appreciated.

**Comment by SteveKunG** [comment]
It already fixed in 1.3.0-Pre-3

**Comment by ktole1999** [comment]
Awesome many thanks

Sent from Outlook




On Tue, Nov 24, 2015 at 12:04 AM -0800, "SteveKunG" <notifications@github.com> wrote:





It already fixed in 1.3.0-Pre-3

---

**Comment by loiclavoie** [comment]
Out of curiosity, what's the real name of this item? (One of the pack I play hasn't updated that mod yet, so I still have that item in one of my chest)

**Comment by SteveKunG** [comment]
That is Feces. But when you using latest of my mod, item will disappear from your chest because I was renamed it to item.feces.name.
